sudo: required
services:
  - docker

before_install:
  - docker build -t ruona/react-docker-play-ground -f Dockerfile.dev .

script:
  - docker run ruona/react-docker-play-ground npm run test -- --coverage
