sudo: required
services:
  - docker

before_install:
  - docker build -t ruona/react-docker-play-ground -f Dockerfile.dev .

script:
  - docker run ruona/react-docker-play-ground npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name:
